# RNN Shapes

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [21]:
from tensorflow.keras import Sequential,Input
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import Dense,Flatten,SimpleRNN

### IMP FACTORS TO REMEMBER

#### N = No of samples
#### T = Length of sequence 
#### D = No if input featues
#### M = No of hidden units
#### K = No of output Units

In [22]:
N=1
D=3
T=10
M=5
K=2

X= np.random.randn(N,T,D)

In [23]:
print(X)

[[[-2.48604969  0.30764991  0.687804  ]
  [ 0.02657688 -0.09337135  1.81981837]
  [-0.80182939  0.39404859 -0.34575991]
  [-1.43917276 -0.24351747  1.31672633]
  [-2.85071672  0.92622721  0.44611246]
  [-1.24624113 -1.34323576 -1.68572314]
  [-0.39335016  0.83609414  0.42888107]
  [ 3.06778171  1.98172241 -0.12708853]
  [-0.2056615   0.53915734 -0.05174516]
  [-1.0082647   0.35765701  3.35490549]]]


In [24]:
model= Sequential()

model.add(Input(shape=(T,D)))

model.add(SimpleRNN(M,activation='relu'))

model.add(Dense(K))

In [25]:
yhat=model.predict(X)

1/1 [==============================] - 0s 184ms/step


In [26]:
yhat

array([[0.4321339, 1.672685 ]], dtype=float32)

In [27]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_2 (SimpleRNN)    (None, 5)                 45        
                                                                 
 dense_2 (Dense)             (None, 2)                 12        
                                                                 
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [28]:
a,b=model.layers[1].get_weights()
print(f'a shape {a.shape}, b shape {b.shape}')

a shape (5, 2), b shape (2,)
